支持配置多个label并输出多个json文件
xaoxuu/issues-json-generator pull request #2
Opened 2022-11-13 11:07 UTC by BeaCox

顺便去掉了requiements.txt中的多余内容

2022-11-13 15:20 UTC, xaoxuu requested changes

2022-11-13 15:20 UTC, xaoxuu commented on generator/main.py
> +version = 'v3'
感觉应该不用换版本号，如果内容不变，就文件名字变了，api那边适配一下就好

2022-11-13 16:25 UTC, BeaCox commented
有道理，改回v2了

2022-11-13 16:46 UTC, BeaCox reviewed
done

2022-11-14 06:08 UTC, xaoxuu approved these changes
感谢大佬，等我有时间了把api那边兼容一下之后合并

2022-11-14 06:22 UTC, BeaCox commented
> 感谢大佬，等我有时间了把api那边兼容一下之后合并

🤣就改了一点点，大佬辛苦！

2022-11-14 12:33 UTC, xaoxuu commented
大佬能不能加个逻辑，就是只有一个 label 的时候生成 `data.json` 🥹

目前除了友链，朋友圈也是输出 `data.json` 的，没有多标签需求的话，固定用这个名字会使 api 那边简单很多，老用户不需要做任何改变了。

2022-11-14 17:18 UTC, merged